name: Auto Tag on Commit

on:
  push:
    branches:
      - master

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract version from commit message
        id: extract
        run: |
          msg=$(git log -1 --pretty=%B)
          echo "Commit message: $msg"

          if [[ $msg =~ release:\ (v[0-9]+\.[0-9]+\.[0-9]+) ]]; then
            echo "version=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
            echo "✅ Found version: ${BASH_REMATCH[1]}"
          elif [[ $msg =~ release: ]]; then
            echo "❌ Invalid release commit format. Use: release: vX.Y.Z"
            exit 1
          else
            echo "ℹ️ No release commit. Skipping."
            exit 0
          fi

      - name: Create tag
        if: steps.extract.outputs.version != ''
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ steps.extract.outputs.version }}
          git push origin ${{ steps.extract.outputs.version }}
